export const MODULE_ORDER = ['Dashboard', 'Argent', 'Vente objets', 'Items', 'Transactions', 'Transactions récentes', 'Activité', 'FOUR', 'Drogues', 'Tablette', 'Cigarette', 'Membres', 'Logs', 'Compte', 'Autres'] as const;

export const SECTION_ORDER = ['Vue', 'Historique', 'Mouvements', 'Vente objets', 'Création', 'Passages', 'Modification / Annulation', 'Sessions', 'Transactions', 'Messages', 'Stats', 'Logs', 'Sécurité', 'Gestion', 'Technique'] as const;

type PermissionInfo = { module: string; section: string; label: string; hint: string };

export const PERMISSION_LABELS: Record<string, PermissionInfo> = {
  'dashboard.preview': { module: 'Dashboard', section: 'Vue', label: 'Voir la bulle Dashboard', hint: 'Permet d’afficher la bulle Dashboard.' },
  'dashboard.access': { module: 'Dashboard', section: 'Vue', label: 'Accéder au dashboard', hint: 'Permet d’ouvrir le dashboard.' },
  'dashboard.view': { module: 'Dashboard', section: 'Vue', label: 'Voir les widgets Dashboard', hint: 'Permet d’afficher les widgets du dashboard.' },
  'dashboard.stock.movements.preview': { module: 'Dashboard', section: 'Vue', label: 'Voir le bloc stock récent', hint: 'Permet d’afficher le bloc Derniers mouvements de stock.' },
  'dashboard.stock.movements.access': { module: 'Dashboard', section: 'Vue', label: 'Lire le bloc stock récent', hint: 'Permet de consulter les données du bloc Derniers mouvements de stock.' },
  'dashboard.money.movements.preview': { module: 'Dashboard', section: 'Vue', label: 'Voir le bloc cash récent', hint: 'Permet d’afficher le bloc Derniers mouvements d’argent.' },
  'dashboard.money.movements.access': { module: 'Dashboard', section: 'Vue', label: 'Lire le bloc cash récent', hint: 'Permet de consulter les données du bloc Derniers mouvements d’argent.' },

  'money.preview': { module: 'Argent', section: 'Vue', label: 'Voir la bulle Argent', hint: 'Permet d’afficher la bulle Argent sur le dashboard.' },
  'money.access': { module: 'Argent', section: 'Vue', label: 'Accéder au module Argent', hint: 'Permet d’ouvrir la page Argent.' },
  'money.history.view': { module: 'Argent', section: 'Historique', label: 'Voir l’historique argent', hint: 'Permet de consulter l’historique des mouvements d’argent.' },
  'money.movements.view': { module: 'Argent', section: 'Mouvements', label: 'Voir les mouvements argent globaux', hint: 'Permet d’ouvrir la page globale des mouvements argent.' },
  'money.edit': { module: 'Argent', section: 'Modification / Annulation', label: 'Créer / modifier des mouvements cash', hint: 'Permet de créer des mouvements manuels d’argent.' },
  'money.pay.access': { module: 'Argent', section: 'Vue', label: 'Voir la page Paye', hint: 'Permet d’ouvrir la page Paye dans le module Argent.' },
  'money.pay.create': { module: 'Argent', section: 'Création', label: 'Créer / valider une paye', hint: 'Permet de payer un membre depuis la caisse groupe.' },
  'money.pay.history.view': { module: 'Argent', section: 'Historique', label: 'Voir l’historique des payes', hint: 'Permet de consulter l’historique des payes membres.' },
  'money.pay.logs.view': { module: 'Argent', section: 'Logs', label: 'Voir les logs paye', hint: 'Permet de consulter les logs des payes.' },
  'money.quick_sale.access': { module: 'Vente objets', section: 'Vue', label: 'Accéder à Vente objets (compatibilité)', hint: 'Alias historique: ouvre le module Vente objets.' },
  'money.quick_sale.create': { module: 'Vente objets', section: 'Création', label: 'Valider une vente objets (compatibilité)', hint: 'Alias historique: autorise la création/validation de vente objets.' },
  'money.quick_sale.details.view': { module: 'Vente objets', section: 'Historique', label: 'Voir les détails ventes objets (compatibilité)', hint: 'Alias historique: autorise la lecture du détail et historique des ventes objets.' },
  'money.quick_sale.logs.view': { module: 'Vente objets', section: 'Logs', label: 'Voir les logs vente objets (compatibilité)', hint: 'Alias historique: autorise la lecture des logs Vente objets.' },

  'items.preview': { module: 'Items', section: 'Vue', label: 'Voir la bulle Items', hint: 'Permet d’afficher la bulle Items.' },
  'items.access': { module: 'Items', section: 'Vue', label: 'Accéder au module Items', hint: 'Permet d’ouvrir le module Items.' },
  'items.movements.view': { module: 'Items', section: 'Mouvements', label: 'Voir les mouvements stock globaux', hint: 'Permet d’ouvrir la page globale des mouvements stock.' },
  'items.create': { module: 'Items', section: 'Création', label: 'Créer un item', hint: 'Permet d’ajouter un item.' },
  'items.edit': { module: 'Items', section: 'Modification / Annulation', label: 'Modifier un item', hint: 'Permet de modifier un item.' },
  'items.delete': { module: 'Items', section: 'Modification / Annulation', label: 'Supprimer un item', hint: 'Permet de supprimer un item.' },


  'sale.objects.preview': { module: 'Vente objets', section: 'Vue', label: 'Voir la bulle Vente objets', hint: 'Permet d’afficher la bulle Vente objets sur le dashboard.' },
  'sale.objects.access': { module: 'Vente objets', section: 'Vue', label: 'Accéder à la page Vente objets', hint: 'Permet d’ouvrir le module Vente objets.' },
  'sale.objects.create': { module: 'Vente objets', section: 'Création', label: 'Créer / valider une vente objets', hint: 'Permet de créer une nouvelle vente objets.' },
  'sale.objects.receive': { module: 'Vente objets', section: 'Modification / Annulation', label: 'Marquer une vente pawnshop comme reçue', hint: 'Permet de confirmer la réception d’argent des ventes pawnshop.' },
  'sale.objects.edit.own': { module: 'Vente objets', section: 'Modification / Annulation', label: 'Modifier ses ventes objets', hint: 'Permet de modifier uniquement ses ventes objets.' },
  'sale.objects.edit.any': { module: 'Vente objets', section: 'Modification / Annulation', label: 'Modifier toutes les ventes objets', hint: 'Permet de modifier toutes les ventes objets.' },
  'sale.objects.cancel.own': { module: 'Vente objets', section: 'Modification / Annulation', label: 'Annuler ses ventes objets', hint: 'Permet d’annuler uniquement ses ventes objets.' },
  'sale.objects.cancel.any': { module: 'Vente objets', section: 'Modification / Annulation', label: 'Annuler toutes les ventes objets', hint: 'Permet d’annuler toutes les ventes objets.' },
  'sale.objects.history.view': { module: 'Vente objets', section: 'Historique', label: 'Voir l’historique Vente objets', hint: 'Permet de consulter l’historique des ventes objets.' },

  'transactions.preview': { module: 'Transactions', section: 'Vue', label: 'Voir la bulle Transactions', hint: 'Permet d’afficher la bulle Transactions.' },
  'transactions.access': { module: 'Transactions', section: 'Vue', label: 'Accéder à Transactions', hint: 'Permet d’ouvrir la page Transactions.' },
  'transactions.create': { module: 'Transactions', section: 'Création', label: 'Créer une transaction', hint: 'Permet de créer une transaction.' },
  'transactions.edit.own': { module: 'Transactions', section: 'Modification / Annulation', label: 'Modifier ses transactions', hint: 'Permet de modifier uniquement ses transactions.' },
  'transactions.cancel.own': { module: 'Transactions', section: 'Modification / Annulation', label: 'Annuler ses transactions', hint: 'Permet d’annuler uniquement ses transactions.' },
  'transactions.edit.any': { module: 'Transactions', section: 'Modification / Annulation', label: 'Modifier toutes les transactions', hint: 'Permet de modifier toutes les transactions.' },
  'transactions.cancel.any': { module: 'Transactions', section: 'Modification / Annulation', label: 'Annuler toutes les transactions', hint: 'Permet d’annuler toutes les transactions.' },
  'transactions.manage.own': { module: 'Transactions', section: 'Modification / Annulation', label: 'Modifier ses transactions (compatibilité)', hint: 'Alias historique: équivaut à modifier/annuler ses transactions.' },
  'transactions.manage.any': { module: 'Transactions', section: 'Modification / Annulation', label: 'Modifier toutes les transactions (compatibilité)', hint: 'Alias historique: équivaut à modifier/annuler toutes les transactions.' },

  'transactions.recent.preview': { module: 'Transactions récentes', section: 'Vue', label: 'Voir la bulle Transactions récentes', hint: 'Permet d’afficher la bulle Transactions récentes.' },
  'transactions.recent.access': { module: 'Transactions récentes', section: 'Historique', label: 'Accéder à Transactions récentes', hint: 'Permet d’ouvrir la page Transactions récentes.' },
  'transactions.recent.edit.own': { module: 'Transactions récentes', section: 'Modification / Annulation', label: 'Modifier ses transactions récentes', hint: 'Permet de modifier uniquement ses transactions récentes.' },
  'transactions.recent.cancel.own': { module: 'Transactions récentes', section: 'Modification / Annulation', label: 'Annuler ses transactions récentes', hint: 'Permet d’annuler uniquement ses transactions récentes.' },
  'transactions.recent.edit.any': { module: 'Transactions récentes', section: 'Modification / Annulation', label: 'Modifier toutes les transactions récentes', hint: 'Permet de modifier toutes les transactions récentes.' },
  'transactions.recent.cancel.any': { module: 'Transactions récentes', section: 'Modification / Annulation', label: 'Annuler toutes les transactions récentes', hint: 'Permet d’annuler toutes les transactions récentes.' },
  'transactions.recent.manage.own': { module: 'Transactions récentes', section: 'Modification / Annulation', label: 'Modifier ses transactions récentes (compatibilité)', hint: 'Alias historique: équivaut à modifier/annuler ses transactions récentes.' },
  'transactions.recent.manage.any': { module: 'Transactions récentes', section: 'Modification / Annulation', label: 'Modifier toutes les transactions récentes (compatibilité)', hint: 'Alias historique: équivaut à modifier/annuler toutes les transactions récentes.' },

  'activity.preview': { module: 'Activité', section: 'Vue', label: 'Voir la bulle Activité', hint: 'Permet d’afficher la bulle Activité.' },
  'activity.access': { module: 'Activité', section: 'Vue', label: 'Accéder au module Activité', hint: 'Permet d’ouvrir le module Activité.' },
  'activity.view': { module: 'Activité', section: 'Historique', label: 'Voir les activités', hint: 'Permet de consulter les activités.' },
  'activity.create': { module: 'Activité', section: 'Création', label: 'Créer une activité', hint: 'Permet de créer une activité.' },
  'activity.edit.own': { module: 'Activité', section: 'Modification / Annulation', label: 'Modifier ses activités', hint: 'Permet de modifier uniquement ses activités.' },
  'activity.cancel.own': { module: 'Activité', section: 'Modification / Annulation', label: 'Annuler ses activités', hint: 'Permet d’annuler uniquement ses activités.' },
  'activity.edit.any': { module: 'Activité', section: 'Modification / Annulation', label: 'Modifier toutes les activités', hint: 'Permet de modifier toutes les activités.' },
  'activity.cancel.any': { module: 'Activité', section: 'Modification / Annulation', label: 'Annuler toutes les activités', hint: 'Permet d’annuler toutes les activités.' },
  'activity.manage.own': { module: 'Activité', section: 'Modification / Annulation', label: 'Modifier ses activités (compatibilité)', hint: 'Alias historique: équivaut à modifier/annuler ses activités.' },
  'activity.manage.any': { module: 'Activité', section: 'Modification / Annulation', label: 'Modifier toutes les activités (compatibilité)', hint: 'Alias historique: équivaut à modifier/annuler toutes les activités.' },
  'activity.stats.view': { module: 'Activité', section: 'Stats', label: 'Voir les stats Activité', hint: 'Permet de consulter les statistiques Activité.' },
  'activity.logs.view': { module: 'Activité', section: 'Logs', label: 'Voir les logs Activité', hint: 'Permet de consulter les logs Activité.' },

  'four.preview': { module: 'FOUR', section: 'Vue', label: 'Voir la bulle FOUR', hint: 'Permet d’afficher la bulle FOUR sur le dashboard.' },
  'four.access': { module: 'FOUR', section: 'Vue', label: 'Accéder à la page FOUR', hint: 'Permet d’ouvrir le module FOUR.' },
  'four.open': { module: 'FOUR', section: 'Sessions', label: 'Ouvrir une session FOUR', hint: 'Permet d’ouvrir une session FOUR.' },
  'four.close': { module: 'FOUR', section: 'Sessions', label: 'Fermer une session FOUR', hint: 'Permet de clôturer une session FOUR.' },
  'four.cash.add': { module: 'FOUR', section: 'Sessions', label: 'Ajouter du cash à la session FOUR', hint: 'Permet d’ajouter du cash dans la session FOUR ouverte.' },
  'four.add_movement': { module: 'FOUR', section: 'Transactions', label: 'Ajouter un mouvement FOUR', hint: 'Permet d’ajouter des lignes dans la transaction FOUR en cours.' },
  'four.transaction.validate': { module: 'FOUR', section: 'Transactions', label: 'Valider une transaction FOUR', hint: 'Permet de valider une transaction dans une session FOUR.' },
  'four.transaction.edit.own': { module: 'FOUR', section: 'Transactions', label: 'Modifier ses transactions FOUR', hint: 'Permet de modifier uniquement ses transactions FOUR.' },
  'four.transaction.cancel.own': { module: 'FOUR', section: 'Transactions', label: 'Annuler ses transactions FOUR', hint: 'Permet d’annuler uniquement ses transactions FOUR.' },
  'four.transaction.edit.any': { module: 'FOUR', section: 'Transactions', label: 'Modifier toutes les transactions FOUR', hint: 'Permet de modifier toutes les transactions FOUR.' },
  'four.transaction.cancel.any': { module: 'FOUR', section: 'Transactions', label: 'Annuler toutes les transactions FOUR', hint: 'Permet d’annuler toutes les transactions FOUR.' },
  'four.transaction.manage': { module: 'FOUR', section: 'Transactions', label: 'Modifier ses transactions FOUR (compatibilité)', hint: 'Alias historique: équivaut à modifier/annuler ses transactions FOUR.' },
  'four.transaction.manage.own': { module: 'FOUR', section: 'Transactions', label: 'Modifier ses transactions FOUR (compatibilité)', hint: 'Alias historique: équivaut à modifier/annuler ses transactions FOUR.' },
  'four.transaction.manage.any': { module: 'FOUR', section: 'Transactions', label: 'Modifier toutes les transactions FOUR (compatibilité)', hint: 'Alias historique: équivaut à modifier/annuler toutes les transactions FOUR.' },
  'four.history.view': { module: 'FOUR', section: 'Historique', label: 'Voir l’historique FOUR', hint: 'Permet de consulter l’historique des sessions FOUR.' },
  'four.stats.view': { module: 'FOUR', section: 'Stats', label: 'Voir les stats FOUR', hint: 'Permet de consulter les statistiques FOUR.' },
  'four.messages.view': { module: 'FOUR', section: 'Messages', label: 'Voir les messages FOUR', hint: 'Permet d’afficher les messages FOUR.' },
  'four.messages.manage': { module: 'FOUR', section: 'Messages', label: 'Gérer les messages FOUR', hint: 'Permet de créer, modifier et supprimer les messages FOUR.' },
  'four.logs.view': { module: 'FOUR', section: 'Logs', label: 'Voir les logs FOUR', hint: 'Permet de consulter les logs FOUR.' },

  'drugs.preview': { module: 'Drogues', section: 'Vue', label: 'Voir la bulle Drogues', hint: 'Permet d’afficher la bulle Drogues.' },
  'drugs.access': { module: 'Drogues', section: 'Vue', label: 'Accéder à Drogues', hint: 'Permet d’ouvrir le module Drogues.' },
  'drugs.transfo.view': { module: 'Drogues', section: 'Transfo', label: 'Voir les transfos', hint: 'Permet de consulter les transfos.' },
  'drugs.transfo.create': { module: 'Drogues', section: 'Transfo', label: 'Créer une transfo', hint: 'Permet de créer une transfo.' },
  'drugs.transfo.receive.validate': { module: 'Drogues', section: 'Transfo', label: 'Valider une réception de transfo', hint: 'Permet de valider la réception d’une transfo.' },
  'drugs.transfo.cancel.own': { module: 'Drogues', section: 'Transfo', label: 'Annuler ses propres transfos', hint: 'Permet d’annuler ses propres transfos.' },
  'drugs.transfo.cancel.any': { module: 'Drogues', section: 'Transfo', label: 'Annuler toutes les transfos', hint: 'Permet d’annuler toutes les transfos.' },
  'drugs.transfo.edit.own': { module: 'Drogues', section: 'Transfo', label: 'Modifier ses propres transfos', hint: 'Permet de modifier ses propres transfos.' },
  'drugs.transfo.edit.any': { module: 'Drogues', section: 'Transfo', label: 'Modifier toutes les transfos', hint: 'Permet de modifier toutes les transfos.' },
  'drugs.transfo.logs.view': { module: 'Drogues', section: 'Logs', label: 'Voir les logs transfo', hint: 'Permet de consulter les logs transfo.' },
  'drugs.transfo.stats.view': { module: 'Drogues', section: 'Stats', label: 'Voir les stats transfo', hint: 'Permet de consulter les statistiques transfo.' },
  'drugs.sales.preview': { module: 'Drogues', section: 'Vente drogue', label: 'Voir la bulle Vente drogue', hint: 'Permet d’afficher la section Vente drogue.' },
  'drugs.sales.view': { module: 'Drogues', section: 'Vente drogue', label: 'Voir les ventes drogue', hint: 'Permet de consulter les ventes drogue.' },
  'drugs.sales.create': { module: 'Drogues', section: 'Vente drogue', label: 'Créer une vente drogue', hint: 'Permet de créer une vente drogue.' },
  'drugs.sales.edit.own': { module: 'Drogues', section: 'Vente drogue', label: 'Modifier ses propres ventes drogue', hint: 'Permet de modifier ses propres ventes drogue.' },
  'drugs.sales.edit.any': { module: 'Drogues', section: 'Vente drogue', label: 'Modifier toutes les ventes drogue', hint: 'Permet de modifier toutes les ventes drogue.' },
  'drugs.sales.cancel.own': { module: 'Drogues', section: 'Vente drogue', label: 'Annuler ses propres ventes drogue', hint: 'Permet d’annuler ses propres ventes drogue.' },
  'drugs.sales.cancel.any': { module: 'Drogues', section: 'Vente drogue', label: 'Annuler toutes les ventes drogue', hint: 'Permet d’annuler toutes les ventes drogue.' },
  'drugs.sales.logs.view': { module: 'Drogues', section: 'Logs', label: 'Voir les logs vente drogue', hint: 'Permet de consulter les logs vente drogue.' },
  'drugs.sales.stats.view': { module: 'Drogues', section: 'Stats', label: 'Voir les stats vente drogue', hint: 'Permet de consulter les statistiques vente drogue.' },
  'drugs.production.access': { module: 'Drogues', section: 'Production', label: 'Accéder à Production', hint: 'Permet d’afficher la section production.' },
  'drugs.production.create': { module: 'Drogues', section: 'Production', label: 'Créer une production drogue', hint: 'Permet de créer une production drogue.' },
  'drugs.production.coke.create': { module: 'Drogues', section: 'Production', label: 'Créer une production Coke', hint: 'Permet de valider une production Coke.' },
  'drugs.production.meth.create': { module: 'Drogues', section: 'Production', label: 'Créer une production Meth', hint: 'Permet de valider une production Meth.' },
  'drugs.production.edit.own': { module: 'Drogues', section: 'Production', label: 'Modifier ses propres productions', hint: 'Permet de modifier ses propres productions.' },
  'drugs.production.edit.any': { module: 'Drogues', section: 'Production', label: 'Modifier toutes les productions', hint: 'Permet de modifier toutes les productions.' },
  'drugs.production.cancel.own': { module: 'Drogues', section: 'Production', label: 'Annuler ses propres productions', hint: 'Permet d’annuler ses propres productions.' },
  'drugs.production.cancel.any': { module: 'Drogues', section: 'Production', label: 'Annuler toutes les productions', hint: 'Permet d’annuler toutes les productions.' },
  'drugs.production.history.view': { module: 'Drogues', section: 'Production', label: 'Voir l’historique des productions', hint: 'Permet de consulter l’historique des productions.' },
  'drugs.logs.view': { module: 'Drogues', section: 'Logs', label: 'Voir les logs Drogues', hint: 'Permet de consulter les logs du module Drogues.' },
  'drugs.stats.view': { module: 'Drogues', section: 'Stats', label: 'Voir les stats Drogues', hint: 'Permet de consulter les statistiques Drogues.' },

  'tablet.preview': { module: 'Tablette', section: 'Vue', label: 'Voir la bulle Tablette', hint: 'Permet d’afficher la bulle Tablette.' },
  'tablet.access': { module: 'Tablette', section: 'Vue', label: 'Accéder à Tablette', hint: 'Permet d’ouvrir le module Tablette.' },
  'tablet.daily.manage': { module: 'Tablette', section: 'Modification / Annulation', label: 'Gérer le dépôt journalier', hint: 'Permet de gérer le dépôt du matin.' },
  'tablet.passage.create': { module: 'Tablette', section: 'Création', label: 'Créer un passage tablette', hint: 'Permet de créer un passage tablette.' },
  'tablet.stats.view': { module: 'Tablette', section: 'Stats', label: 'Voir les stats Tablette', hint: 'Permet de consulter les stats Tablette.' },
  'tablet.logs.view': { module: 'Tablette', section: 'Logs', label: 'Voir les logs Tablette', hint: 'Permet de consulter les logs Tablette.' },

  'cigarette.preview': { module: 'Cigarette', section: 'Vue', label: 'Voir la bulle Cigarette', hint: 'Permet d’afficher la bulle Cigarette sur le dashboard.' },
  'cigarette.access': { module: 'Cigarette', section: 'Vue', label: 'Accéder au module Cigarette', hint: 'Permet d’ouvrir la page Cigarette.' },
  'cigarette.passage.create': { module: 'Cigarette', section: 'Passages', label: 'Créer un passage Cigarette', hint: 'Permet d’enregistrer un passage de vente cigarette sur la journée en cours.' },
  'cigarette.passage.create.any': { module: 'Cigarette', section: 'Passages', label: 'Créer un passage Cigarette pour un autre membre', hint: 'Permet d’enregistrer un passage cigarette au nom d’un autre membre.' },
  'cigarette.history.view': { module: 'Cigarette', section: 'Historique', label: 'Voir l’historique Cigarette', hint: 'Permet de consulter les passages cigarette de la journée.' },
  'cigarette.stats.view': { module: 'Cigarette', section: 'Stats', label: 'Voir les stats Cigarette', hint: 'Permet de consulter les statistiques Cigarette.' },
  'cigarette.logs.view': { module: 'Cigarette', section: 'Logs', label: 'Voir les logs Cigarette', hint: 'Permet de consulter les logs du module Cigarette.' },
  'cigarette.daily.manage': { module: 'Cigarette', section: 'Gestion', label: 'Gérer / réinitialiser la journée Cigarette', hint: 'Permet de réinitialiser la journée Cigarette (dépôt et passages).' },
  'cigarette.edit.own': { module: 'Cigarette', section: 'Gestion', label: 'Modifier / annuler ses propres passages Cigarette', hint: 'Permet de corriger ou annuler uniquement ses propres passages Cigarette.' },
  'cigarette.edit.any': { module: 'Cigarette', section: 'Gestion', label: 'Modifier / annuler tous les passages Cigarette', hint: 'Permet de corriger ou annuler tous les passages Cigarette.' },

  'members.preview': { module: 'Membres', section: 'Vue', label: 'Voir la bulle Membres', hint: 'Permet d’afficher la bulle Membres.' },
  'members.access': { module: 'Membres', section: 'Vue', label: 'Accéder à Membres', hint: 'Permet d’ouvrir le module Membres.' },
  'members.view': { module: 'Membres', section: 'Vue', label: 'Voir les membres', hint: 'Permet de consulter les membres.' },
  'members.create': { module: 'Membres', section: 'Création', label: 'Créer un membre', hint: 'Permet de créer un membre.' },
  'members.edit': { module: 'Membres', section: 'Modification / Annulation', label: 'Modifier un membre', hint: 'Permet de modifier un membre.' },
  'members.delete': { module: 'Membres', section: 'Modification / Annulation', label: 'Supprimer un membre', hint: 'Permet de supprimer un membre.' },
  'members.activities.view': { module: 'Membres', section: 'Historique', label: 'Voir les activités d’un membre', hint: 'Permet d’ouvrir la page des activités d’un membre.' },
  'members.password.view': { module: 'Membres', section: 'Sécurité', label: 'Voir le mot de passe membre', hint: 'Permet d’afficher le mot de passe d’un membre.' },
  'members.password.copy': { module: 'Membres', section: 'Sécurité', label: 'Copier le mot de passe membre', hint: 'Permet de copier le mot de passe d’un membre.' },
  'members.credentials.copy': { module: 'Membres', section: 'Sécurité', label: 'Copier les identifiants membre', hint: 'Permet de copier le message complet d’accès tablette.' },
  'members.password.edit': { module: 'Membres', section: 'Sécurité', label: 'Modifier le mot de passe membre', hint: 'Permet de modifier le mot de passe d’un membre.' },
  'roles.manage': { module: 'Membres', section: 'Gestion', label: 'Gérer rôles et permissions', hint: 'Permet de gérer les rôles et permissions.' },

  'logs.preview': { module: 'Logs', section: 'Vue', label: 'Voir la bulle Logs', hint: 'Permet d’afficher la bulle Logs.' },
  'logs.access': { module: 'Logs', section: 'Vue', label: 'Accéder à Logs', hint: 'Permet d’ouvrir la page Logs.' },
  'logs.view': { module: 'Logs', section: 'Logs', label: 'Voir les logs', hint: 'Permet de consulter les logs applicatifs.' },
  'logs.webhook.manage': { module: 'Logs', section: 'Technique', label: 'Gérer le webhook logs', hint: 'Permet de configurer le webhook Discord des logs.' },

  'account.password.update': { module: 'Compte', section: 'Sécurité', label: 'Modifier son mot de passe', hint: 'Permet de modifier son mot de passe.' }
};

export function describePermission(permissionName: string): PermissionInfo {
  return PERMISSION_LABELS[permissionName] ?? { module: 'Autres', section: 'Technique', label: permissionName.replace(/\./g, ' · '), hint: 'Permission personnalisée.' };
}

export function permissionOrder(permissionName: string) {
  const info = describePermission(permissionName);
  const sectionIdx = SECTION_ORDER.indexOf(info.section as (typeof SECTION_ORDER)[number]);
  return sectionIdx === -1 ? 999 : sectionIdx;
}
